# Generated by Django 3.2.9 on 2021-11-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0003_alter_contact_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='house_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
