# Generated by Django 3.2.9 on 2021-11-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0004_alter_contact_house_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='url',
            field=models.URLField(blank=True, help_text='Format: http://site.com', unique=True),
        ),
    ]
