# Generated by Django 3.2.9 on 2021-11-25 01:06

from django.db import migrations

import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0005_alter_contact_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None,
                                                                 help_text='Enter only real phone number!',
                                                                 max_length=128,
                                                                 region=None,
                                                                 unique=True,
                                                                 verbose_name='Phone'),
        ),
    ]
