# Generated by Django 3.2.9 on 2021-11-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0012_alter_contact_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='url',
            field=models.URLField(blank=True, help_text='Format: http://site.com'),
        ),
    ]
