# Generated by Django 3.2.9 on 2021-11-24 17:22

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Surname')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('street', models.CharField(max_length=50, verbose_name='Street')),
                ('house_number', models.IntegerField(default=None)),
                ('url', models.URLField(unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, region=None, unique=True, verbose_name='Phone')),
                ('profile_pic', models.ImageField(blank=True, default='profile1.png', upload_to='staticfiles/images/profile/')),
            ],
            options={
                'unique_together': {('first_name', 'last_name')},
            },
        ),
    ]
