# Generated by Django 3.2.9 on 2021-11-22 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0002_auto_20211122_1755'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('first_name', 'last_name')},
        ),
    ]
