# Generated by Django 3.2.9 on 2021-11-23 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0003_auto_20211123_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url', to='address_book.person'),
        ),
    ]
