# Generated by Django 3.2.9 on 2021-11-23 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0004_alter_url_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='address_book.person'),
        ),
    ]
