# Generated by Django 3.2.9 on 2021-11-22 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0004_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
