# Generated by Django 3.2.9 on 2021-11-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0005_delete_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1),
        ),
    ]
