# Generated by Django 3.2.9 on 2021-11-23 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0006_alter_person_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='ContactProfile',
        ),
    ]
