# Generated by Django 3.2.9 on 2021-11-23 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0007_rename_userprofile_contactprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, default='profile1.png', upload_to='staticfiles/images/profile/'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='address_book.person'),
        ),
        migrations.AlterField(
            model_name='url',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='address_book.person'),
        ),
    ]
