# Generated by Django 3.2.9 on 2021-11-23 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0008_auto_20211122_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='home_number',
            new_name='house_number',
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('country', 'city', 'street', 'house_number')},
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(choices=[('FB', 'Facebook'), ('LN', 'Linkedin'), ('IN', 'Instagram'), ('GH', 'GitHub'), ('JN', 'Jinni'), ('TW', 'Twitter'), ('WS', 'WebSite')], default=None, max_length=2)),
                ('url', models.URLField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url', to='address_book.person')),
            ],
        ),
    ]
